# -*- coding: utf-8 -*-
"""Copia de Lab5. Programming Paradigms Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYLC8_HAd5x4rtgwLQ0otwPWN61AN0Dx

# Lab5. Programming Paradigms Comparison

**Student Name:** Rios Rivera Sebastián Gilberto  
**Group:** ___3A BIS                                                             
**Date:** 20/05/2026  

---

# Objective

You will solve the same problem using different programming paradigms.

The goal is to understand how the way you think and structure a solution changes depending on the paradigm.



# Required Paradigms

You must implement the solution using ALL of the following paradigms:

1. Imperative Programming  
2. Structured Programming (functions + control structures)  
3. Modular Programming  
4. Object-Oriented Programming (OOP)  
5. Functional Programming (basic level)


# Important Rules

- The SAME problem must be used in all paradigms.
- You must NOT copy-paste the same solution with small changes.
- Each paradigm must show a different way of structuring the solution.
- Each section must include:
  - explanation in your own words
  - working code
  - a personal modification
  - a short reflection


# Problem Description

Describe the problem you will solve:

```text
A system that calculates the average grade of students and determines if they pass or fail.

# 1. 1. Imperative Programming  

## Brief Explanation
It's a paradigm to work step by step instructions using variables and loops.


## Code Example
Complete the steps:
"""

# Given data
grades = [70, 80, 90]
total = 0
# 1. Calculate sum using a loop
for i in grades:
  total += i
average = total / len(grades)

if average >= 70:
  print("pass")
else:
  print("fail")

print("Average: ", average)

"""## Your Modification
What did you change and why?

Example: I added a function to calculate the highest grade and printed it together with the average.


## Reflection
What did you learn from this approach and how does it compare to others?

## 2. Structured Programming (functions + control structures)

##Brief Explanation
It is a paradigm that organizes code to make it easier to read, understand, and maintain.
"""

# --- Constantes ---
PASSING_GRADE = 70

# --- Funciones ---
def calculate_sum(grades: list) -> float:
    total = 0
    for grade in grades:
        total += grade
    return total

def calculate_average(grades: list) -> float:
    return calculate_sum(grades) / len(grades)

def determine_status(average: float) -> str:
    if average >= PASSING_GRADE:
        return "pass"
    else:
        return "fail"

def display_results(average: float, status: str) -> None:
    print(f"Average: {average}")
    print(f"Status:  {status}")

# --- Programa principal ---
def main():
    grades = [70, 80, 90]

    average = calculate_average(grades)
    status  = determine_status(average)

    display_results(average, status)

main()

"""##Your Modification
What did you change and why?

I reorganized the original script using the Structured Programming paradigm. Instead of writing everything in a single block, I split the logic into small functions: one to sum the grades, one to calculate the average, one to check if it's a pass or fail, and one to print the results. I also added a main() function as the entry point and replaced the hardcoded 70 with a constant called PASSING_GRADE.

##Reflection
What did you learn from this approach and how does it compare to others?

This approach makes the code easier to read and modify. If something needs to change, like the passing grade or the output format, you only have to touch one specific function instead of hunting through the whole script.
Compared to a flat script, it's more organized without being more complex. Compared to OOP, it's a better fit here since there's no real need for classes when you're just processing a list of numbers. Structured Programming hits a sweet spot for problems like this one.

##3. Modular Programming
Brief Explanation

It consists of dividing a large program into smaller, independent parts.
"""

# ── módulo: grades ──────────────────────────
PASSING_GRADE = 70

def calculate_average(grades):
    return sum(grades) / len(grades)

def determine_status(average):
    return "pass" if average >= PASSING_GRADE else "fail"
# ── módulo: display ──────────────────────────
def show_results(average, status):
    print(f"Average: {average}")
    print(f"Status:  {status}")
# ── main ──────────────────────────
def main():
    grades = [70, 80, 90]
    average = calculate_average(grades)
    status  = determine_status(average)
    show_results(average, status)

main()

"""##Your Modification

I took the structured version and split it across three separate files. grades.py handles all the logic, display.py handles the output, and main.py just ties everything together using imports. Each file is its own module with a single clear responsibility.

##Reflection

The difference from Structured Programming is subtle but important. Here the separation isn't just between functions — it's between files. Each module can be reused or replaced independently, so if you wanted a different output format you'd only swap out display.py without touching the logic at all.
For a small script like this it might feel like overkill, but the idea scales well. The bigger a project gets, the more this separation pays off.

##4. Object-Oriented Programming (OOP)
Brief Explanation

It is a way of organizing your code based on the real world, grouping data (attributes) and actions (methods) into small entities called objects.
"""

# ── Clase: GradeEvaluator ──────────────────────────
class GradeEvaluator:
    PASSING_GRADE = 70

    def __init__(self, grades):
        self.grades = grades
        self.average = None
        self.status = None

    def calculate_average(self):
        self.average = sum(self.grades) / len(self.grades)

    def determine_status(self):
        self.status = "pass" if self.average >= self.PASSING_GRADE else "fail"

    def show_results(self):
        print(f"Average: {self.average}")
        print(f"Status:  {self.status}")

    def run(self):
        self.calculate_average()
        self.determine_status()
        self.show_results()
    # ── main ──────────────────────────
evaluator = GradeEvaluator([70, 80, 90])
evaluator.run()

"""##Your Modification

I wrapped everything inside a class called GradeEvaluator. The grades go in through __init__, and the average and status are stored as attributes of the object. Each method handles one responsibility just like before, but now they all live inside the class and share data through self instead of passing values around as arguments.

##Reflection

The biggest difference from the previous paradigms is that here the data and the functions that operate on it are bundled together. In Structured and Modular Programming, grades got passed from function to function. Here the object holds the state and the methods just act on it.
For something this small it's still a bit of overkill, but OOP starts to make a lot of sense when you have multiple students, multiple subjects, or want to extend behavior — you'd just create more instances or subclasses without rewriting anything.

##6.Functional Programming (basic level)
Brief Explanation

Functional programming is a way of building software (a paradigm) where everything is based on pure mathematical functions.
"""

# ── funciones puras ──────────────────────────
PASSING_GRADE = 70

def calculate_average(grades):
    return sum(grades) / len(grades)

def determine_status(average):
    return "pass" if average >= PASSING_GRADE else "fail"

def format_results(average, status):
    return f"Average: {average}\nStatus:  {status}"
# ── main ──────────────────────────
grades = [70, 80, 90]

average = calculate_average(grades)
status  = determine_status(average)
output  = format_results(average, status)

print(output)

"""##Your Modification

I rewrote the program using pure functions — each function only depends on its inputs and always returns the same output for the same input, without modifying anything outside itself. The key change is that format_results now returns a string instead of printing directly, keeping it free of side effects. The only print lives in main, isolated from the logic.

##Reflection

It looks similar to Structured Programming on the surface, but the discipline is stricter: no shared state, no side effects inside functions, data just flows through. The real difference shows when you scale up.
"""